# k8s/neo4j-loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: neo4j-loadbalancer
  namespace: neo4j
spec:
  type: LoadBalancer
  selector:
    app: neo4j
  ports:
    - port: 7474
      targetPort: 7474
      protocol: TCP
      name: http
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: bolt