# k8s/neo4j-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: neo4j
spec:
  ports:
    - port: 7474
      targetPort: 7474
      protocol: TCP
      name: http
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: bolt
  selector:
    app: neo4j